#需要使用的配置文件
spring:
  profiles:
    active: dev

# 实际生产中通常不直接写在配置文件里面,而是通过应用的启动参数传递，并且需要定期修改。
jwt:
  header: JWTHeaderName # 可自定义，一般是Authorization：Bearer [token]
  secret: aabbccdd
  expiration: 3600000

auth-server: http://localhost:8001 # authorization服务地址


security:
  oauth2:
    client:
      user-authorization-uri: ${auth-server}/oauth/authorize #请求认证的地址
      access-token-uri: ${auth-server}/oauth/token #请求令牌的地址
      client-id: client1
      client-secret: 123456
      scope: all
    resource:
      token-info-uri: ${auth-server}/oauth/check_token
    sso:
      login-path: /login #指向登录页面的路径，即OAuth2授权服务器触发重定向到客户端的路径 ，默认为 /login

server:
  servlet:
    session:
      cookie:
        name: OAUTH2CLIENTSESSION  # 解决  Possible CSRF detected - state parameter was required but no state could be found  问题


