server:
  port: 8888
  servlet:
    session:
      timeout: 10s
      cookie:
        http-only: true
        secure: false

spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  security:
    loginType: JSON
#    user:
#      name: admin
#      password: password
#      roles: ADMIN,USER

